version: '3.8'

services:
  backend:
    image: aahilnj/infosys-backend:latest
    platform: linux/amd64
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"

  frontend:
    image: aahilnj/infosys-frontend:latest
    platform: linux/amd64
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend